name: heart
description: "Another fitness tracker"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.10.0"
  flutter: "3.38.3"

workspace:
  - "shared/heart_api"
  - "shared/heart_db"
  - "shared/heart_charts"
  - "shared/heart_language"
  - "shared/heart_models"
  - "shared/heart_state"

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.4.1
  feedback: ^3.1.0
  firebase_analytics: 12.0.0
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.8.1
  google_sign_in_web: 1.0.0 # required for the sign-in button on the web
  heart_api:
  heart_charts:
  heart_db:
  heart_language:
  heart_models:
  heart_state:
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: any
  logging: ^1.3.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  sentry_flutter: ^9.8.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  test: any
  firebase_auth_mocks: ^0.15.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 200

    - family: "Noto Sans"
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf

    - family: "Daydream"
      fonts:
        - asset: assets/fonts/Daydream.ttf
          weight: 400
          style: normal

    - family: "Icons"
      fonts:
        - asset: assets/fonts/Icons.ttf
