name: heart_api
description: "API wrapper"
version: 0.0.1
homepage: ""
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  heart_models:
    path: "../heart_models"
  http: 1.6.0
  network_utils:
    git:
      url: "https://github.com/kit-g/dart-network-utils.git"
      ref: "0e1fa2e748581d7d76c5f48c21decb8090ffe8d9"

resolution: workspace

dev_dependencies:
  flutter_lints: ^6.0.0
  test: any
  mockito: ^5.6.1
  build_runner: ^2.10.4
