name: heart_language
description: "Language resource"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  args: ^2.4.2
  csv: ^6.0.0

flutter:
  generate: true