name: heart_db
description: "Heart app's local database"
version: 0.1.0
homepage: 'https://github.com/kit-g/heart-of-yours'
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  heart_models:
    path: '../heart_models'
  logging: ^1.3.0
  path: ^1.9.0
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.0

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
