name: heart_models
description: "Interfaces and data classes"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

resolution: workspace

dev_dependencies:
  flutter_lints: 6.0.0
  test: any
  mockito: ^5.4.2
  build_runner: ^2.4.6
