name: heart_charts
description: "Chart widgets"
version: 0.0.1
homepage: ""
publish_to: none

environment:
  sdk: "^3.6.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
