name: heart_state
description: "State authority"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  flutter:
    sdk: flutter
  google_sign_in: 6.3.0
  heart_models:
    path: '../heart_models'
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.4

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  firebase_auth_mocks: ^0.15.0
  coverage: ^1.3.0
